brokerClusterName = DefaultCluster
brokerName = broker-a
brokerId = 0
# 删除过期文件时间（72 小时，单位：小时）
fileReservedTime = 72
# 是否允许自动创建 Topic（生产建议关闭）
autoCreateTopicEnable = true
# 是否允许自动创建订阅组
autoCreateSubscriptionGroup = true
# 存储路径
storePathRootDir = /home/rocketmq/store
# commitLog 存储路径
storePathCommitLog = /home/rocketmq/store/commitlog
# 消息最大大小（4MB）
maxMessageSize = 4194304
# 刷盘方式：ASYNC_FLUSH（异步）或 SYNC_FLUSH（同步）
flushDiskType = ASYNC_FLUSH
# 消息清理策略：DELETE（过期删除）或 FILE（文件保留）
deleteWhen = 04
# 异步发送失败重试次数
retryTimesWhenSendAsyncFailed = 2
# 发送消息超时（毫秒）
sendMsgTimeout = 3000